version: '3'

services:

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    networks: 
      - app-network
    volumes:
      - ./nginx/templates:/etc/nginx/templates/
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - APP_HOST=http://app:3000
    ports: 
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm i && node index.js"
    networks:
      - app-network
    volumes:
    - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge